import { z } from 'astro:content';
import type { Router } from '../utils/router';

// Zod schema for identity data
export const identitySchema = z.object({
  id: z.string().uuid(),
  name: z.string().min(1, 'Name is required'),
  email: z.string().email('Invalid email').optional(),
  role: z.enum(['user', 'admin', 'readonly']).default('user'),
  avatar: z.string().url().optional(),
  locale: z.enum(['en', 'en-gb']).default('en'),
  timezone: z.string().default('Europe/London'),
  createdAt: z.date().default(new Date()),
  updatedAt: z.date().default(new Date()),
  isVerified: z.boolean().default(false),
});

export type Identity = z.infer<typeof identitySchema>;

export interface IdentityService {
  validate: (data: z.infer<typeof identitySchema>) => identitySchema;
  fromUser: (name: string, email: string, role?: 'user' | 'admin' | 'readonly') => Identity;
  fromSession: (session: any) => Identity | null;
  fromToken: (token: string, session: any) => Identity | null;
  merge: (existing: Identity, updates: Partial<Identity>) => Identity;
}

// Placeholder implementation - to be replaced by actual auth provider
export const defaultIdentityService: IdentityService = {
  validate: (data) => identitySchema.parse(data),
  
  fromUser: (name: string, email: string, role = 'user') => {
    return {
      id: '', // Will be generated by auth provider
      name,
      email,
      role,
      createdAt: new Date(),
      updatedAt: new Date(),
      isVerified: false,
    };
  },
  
  fromSession: (_session: any): Identity | null => {
    return null;
  },
  
  fromToken: (_token: string, _session: any): Identity | null => {
    return null;
  },
  
  merge: (existing, updates) => ({
    ...existing,
    ...updates,
    updatedAt: new Date(),
  }),
};